// Code generated by atomix-go-framework. DO NOT EDIT.
package set

import (
	"context"
	driverapi "github.com/atomix/atomix-api/go/atomix/management/driver"
	set "github.com/atomix/atomix-api/go/atomix/primitive/set"
	"github.com/atomix/atomix-go-framework/pkg/atomix/driver/env"
	"github.com/atomix/atomix-go-framework/pkg/atomix/errors"
	"github.com/atomix/atomix-go-framework/pkg/atomix/logging"
)

var log = logging.GetLogger("atomix", "set")

const Type = "Set"

// NewProxyServer creates a new ProxyServer
func NewProxyServer(registry *ProxyRegistry) set.SetServiceServer {
	return &ProxyServer{
		registry: registry,
	}
}

type ProxyServer struct {
	registry *ProxyRegistry
	env      env.DriverEnv
}

func (s *ProxyServer) Size(ctx context.Context, request *set.SizeRequest) (*set.SizeResponse, error) {
	md, ok := metadata.FromIncomingContext(ctx)
	if !ok {
		return nil, errors.Proto(errors.NewInvalid("missing primitive headers"))
	}
	primitiveName, ok := rsm.GetPrimitiveName(md)
	if !ok {
		return nil, errors.Proto(errors.NewInvalid("missing primitive header"))
	}
	proxyID := driverapi.ProxyId{
		Type: Type,
		Name: primitiveName,
	}
	proxy, err := s.registry.GetProxy(proxyID)
	if err != nil {
		log.Warnf("SizeRequest %+v failed: %v", request, err)
		if errors.IsNotFound(err) {
			return nil, errors.NewUnavailable(err.Error())
		}
		return nil, err
	}
	return proxy.Size(ctx, request)
}

func (s *ProxyServer) Contains(ctx context.Context, request *set.ContainsRequest) (*set.ContainsResponse, error) {
	md, ok := metadata.FromIncomingContext(ctx)
	if !ok {
		return nil, errors.Proto(errors.NewInvalid("missing primitive headers"))
	}
	primitiveName, ok := rsm.GetPrimitiveName(md)
	if !ok {
		return nil, errors.Proto(errors.NewInvalid("missing primitive header"))
	}
	proxyID := driverapi.ProxyId{
		Type: Type,
		Name: primitiveName,
	}
	proxy, err := s.registry.GetProxy(proxyID)
	if err != nil {
		log.Warnf("ContainsRequest %+v failed: %v", request, err)
		if errors.IsNotFound(err) {
			return nil, errors.NewUnavailable(err.Error())
		}
		return nil, err
	}
	return proxy.Contains(ctx, request)
}

func (s *ProxyServer) Add(ctx context.Context, request *set.AddRequest) (*set.AddResponse, error) {
	md, ok := metadata.FromIncomingContext(ctx)
	if !ok {
		return nil, errors.Proto(errors.NewInvalid("missing primitive headers"))
	}
	primitiveName, ok := rsm.GetPrimitiveName(md)
	if !ok {
		return nil, errors.Proto(errors.NewInvalid("missing primitive header"))
	}
	proxyID := driverapi.ProxyId{
		Type: Type,
		Name: primitiveName,
	}
	proxy, err := s.registry.GetProxy(proxyID)
	if err != nil {
		log.Warnf("AddRequest %+v failed: %v", request, err)
		if errors.IsNotFound(err) {
			return nil, errors.NewUnavailable(err.Error())
		}
		return nil, err
	}
	return proxy.Add(ctx, request)
}

func (s *ProxyServer) Remove(ctx context.Context, request *set.RemoveRequest) (*set.RemoveResponse, error) {
	md, ok := metadata.FromIncomingContext(ctx)
	if !ok {
		return nil, errors.Proto(errors.NewInvalid("missing primitive headers"))
	}
	primitiveName, ok := rsm.GetPrimitiveName(md)
	if !ok {
		return nil, errors.Proto(errors.NewInvalid("missing primitive header"))
	}
	proxyID := driverapi.ProxyId{
		Type: Type,
		Name: primitiveName,
	}
	proxy, err := s.registry.GetProxy(proxyID)
	if err != nil {
		log.Warnf("RemoveRequest %+v failed: %v", request, err)
		if errors.IsNotFound(err) {
			return nil, errors.NewUnavailable(err.Error())
		}
		return nil, err
	}
	return proxy.Remove(ctx, request)
}

func (s *ProxyServer) Clear(ctx context.Context, request *set.ClearRequest) (*set.ClearResponse, error) {
	md, ok := metadata.FromIncomingContext(ctx)
	if !ok {
		return nil, errors.Proto(errors.NewInvalid("missing primitive headers"))
	}
	primitiveName, ok := rsm.GetPrimitiveName(md)
	if !ok {
		return nil, errors.Proto(errors.NewInvalid("missing primitive header"))
	}
	proxyID := driverapi.ProxyId{
		Type: Type,
		Name: primitiveName,
	}
	proxy, err := s.registry.GetProxy(proxyID)
	if err != nil {
		log.Warnf("ClearRequest %+v failed: %v", request, err)
		if errors.IsNotFound(err) {
			return nil, errors.NewUnavailable(err.Error())
		}
		return nil, err
	}
	return proxy.Clear(ctx, request)
}

func (s *ProxyServer) Events(request *set.EventsRequest, srv set.SetService_EventsServer) error {
	md, ok := metadata.FromIncomingContext(ctx)
	if !ok {
		return nil, errors.Proto(errors.NewInvalid("missing primitive headers"))
	}
	primitiveName, ok := rsm.GetPrimitiveName(md)
	if !ok {
		return nil, errors.Proto(errors.NewInvalid("missing primitive header"))
	}
	proxyID := driverapi.ProxyId{
		Type: Type,
		Name: primitiveName,
	}
	proxy, err := s.registry.GetProxy(proxyID)
	if err != nil {
		log.Warnf("EventsRequest %+v failed: %v", request, err)
		if errors.IsNotFound(err) {
			return errors.NewUnavailable(err.Error())
		}
		return err
	}
	return proxy.Events(request, srv)
}

func (s *ProxyServer) Elements(request *set.ElementsRequest, srv set.SetService_ElementsServer) error {
	md, ok := metadata.FromIncomingContext(ctx)
	if !ok {
		return nil, errors.Proto(errors.NewInvalid("missing primitive headers"))
	}
	primitiveName, ok := rsm.GetPrimitiveName(md)
	if !ok {
		return nil, errors.Proto(errors.NewInvalid("missing primitive header"))
	}
	proxyID := driverapi.ProxyId{
		Type: Type,
		Name: primitiveName,
	}
	proxy, err := s.registry.GetProxy(proxyID)
	if err != nil {
		log.Warnf("ElementsRequest %+v failed: %v", request, err)
		if errors.IsNotFound(err) {
			return errors.NewUnavailable(err.Error())
		}
		return err
	}
	return proxy.Elements(request, srv)
}
