// Code generated by atomix-go-framework. DO NOT EDIT.

// SPDX-FileCopyrightText: 2019-present Open Networking Foundation <info@opennetworking.org>
//
// SPDX-License-Identifier: Apache-2.0

package indexedmap

import (
	"github.com/atomix/atomix-go-framework/pkg/atomix/errors"
	"github.com/atomix/atomix-go-framework/pkg/atomix/logging"
	"github.com/atomix/atomix-go-framework/pkg/atomix/storage/protocol/rsm"
	"github.com/gogo/protobuf/proto"
	"io"
)

var log = logging.GetLogger("atomix", "indexedmap", "service")

const Type = "IndexedMap"

const (
	sizeOp       = "Size"
	putOp        = "Put"
	getOp        = "Get"
	firstEntryOp = "FirstEntry"
	lastEntryOp  = "LastEntry"
	prevEntryOp  = "PrevEntry"
	nextEntryOp  = "NextEntry"
	removeOp     = "Remove"
	clearOp      = "Clear"
	eventsOp     = "Events"
	entriesOp    = "Entries"
)

var newServiceFunc rsm.NewServiceFunc

func registerServiceFunc(rsmf NewServiceFunc) {
	newServiceFunc = func(context rsm.ServiceContext) rsm.Service {
		return &ServiceAdaptor{
			ServiceContext: context,
			rsm:            rsmf(newServiceContext(context)),
		}
	}
}

type NewServiceFunc func(ServiceContext) Service

// RegisterService registers the election primitive service on the given node
func RegisterService(node *rsm.Node) {
	node.RegisterService(Type, newServiceFunc)
}

type ServiceAdaptor struct {
	rsm.ServiceContext
	rsm Service
}

func (s *ServiceAdaptor) ExecuteCommand(command rsm.Command) {
	switch command.OperationID() {
	case 2:
		p, err := newPutProposal(command)
		if err != nil {
			err = errors.NewInternal(err.Error())
			log.Error(err)
			command.Output(nil, err)
			return
		}

		log.Debugf("Proposal PutProposal %.250s", p)
		response, err := s.rsm.Put(p)
		if err != nil {
			log.Debugf("Proposal PutProposal %.250s failed: %v", p, err)
			command.Output(nil, err)
		} else {
			output, err := proto.Marshal(response)
			if err != nil {
				err = errors.NewInternal(err.Error())
				log.Errorf("Proposal PutProposal %.250s failed: %v", p, err)
				command.Output(nil, err)
			} else {
				log.Debugf("Proposal PutProposal %.250s complete: %.250s", p, response)
				command.Output(output, nil)
			}
		}
		command.Close()
	case 8:
		p, err := newRemoveProposal(command)
		if err != nil {
			err = errors.NewInternal(err.Error())
			log.Error(err)
			command.Output(nil, err)
			return
		}

		log.Debugf("Proposal RemoveProposal %.250s", p)
		response, err := s.rsm.Remove(p)
		if err != nil {
			log.Debugf("Proposal RemoveProposal %.250s failed: %v", p, err)
			command.Output(nil, err)
		} else {
			output, err := proto.Marshal(response)
			if err != nil {
				err = errors.NewInternal(err.Error())
				log.Errorf("Proposal RemoveProposal %.250s failed: %v", p, err)
				command.Output(nil, err)
			} else {
				log.Debugf("Proposal RemoveProposal %.250s complete: %.250s", p, response)
				command.Output(output, nil)
			}
		}
		command.Close()
	case 9:
		p, err := newClearProposal(command)
		if err != nil {
			err = errors.NewInternal(err.Error())
			log.Error(err)
			command.Output(nil, err)
			return
		}

		log.Debugf("Proposal ClearProposal %.250s", p)
		response, err := s.rsm.Clear(p)
		if err != nil {
			log.Debugf("Proposal ClearProposal %.250s failed: %v", p, err)
			command.Output(nil, err)
		} else {
			output, err := proto.Marshal(response)
			if err != nil {
				err = errors.NewInternal(err.Error())
				log.Errorf("Proposal ClearProposal %.250s failed: %v", p, err)
				command.Output(nil, err)
			} else {
				log.Debugf("Proposal ClearProposal %.250s complete: %.250s", p, response)
				command.Output(output, nil)
			}
		}
		command.Close()
	case 10:
		p, err := newEventsProposal(command)
		if err != nil {
			err = errors.NewInternal(err.Error())
			log.Error(err)
			command.Output(nil, err)
			return
		}

		log.Debugf("Proposal EventsProposal %.250s", p)
		s.rsm.Events(p)
	default:
		err := errors.NewNotSupported("unknown operation %d", command.OperationID())
		log.Debug(err)
		command.Output(nil, err)
	}
}

func (s *ServiceAdaptor) ExecuteQuery(query rsm.Query) {
	switch query.OperationID() {
	case 1:
		q, err := newSizeQuery(query)
		if err != nil {
			err = errors.NewInternal(err.Error())
			log.Error(err)
			query.Output(nil, err)
			return
		}

		log.Debugf("Querying SizeQuery %.250s", q)
		response, err := s.rsm.Size(q)
		if err != nil {
			log.Debugf("Querying SizeQuery %.250s failed: %v", q, err)
			query.Output(nil, err)
		} else {
			output, err := proto.Marshal(response)
			if err != nil {
				err = errors.NewInternal(err.Error())
				log.Errorf("Querying SizeQuery %.250s failed: %v", q, err)
				query.Output(nil, err)
			} else {
				log.Debugf("Querying SizeQuery %.250s complete: %+v", q, response)
				query.Output(output, nil)
			}
		}
		query.Close()
	case 3:
		q, err := newGetQuery(query)
		if err != nil {
			err = errors.NewInternal(err.Error())
			log.Error(err)
			query.Output(nil, err)
			return
		}

		log.Debugf("Querying GetQuery %.250s", q)
		response, err := s.rsm.Get(q)
		if err != nil {
			log.Debugf("Querying GetQuery %.250s failed: %v", q, err)
			query.Output(nil, err)
		} else {
			output, err := proto.Marshal(response)
			if err != nil {
				err = errors.NewInternal(err.Error())
				log.Errorf("Querying GetQuery %.250s failed: %v", q, err)
				query.Output(nil, err)
			} else {
				log.Debugf("Querying GetQuery %.250s complete: %+v", q, response)
				query.Output(output, nil)
			}
		}
		query.Close()
	case 4:
		q, err := newFirstEntryQuery(query)
		if err != nil {
			err = errors.NewInternal(err.Error())
			log.Error(err)
			query.Output(nil, err)
			return
		}

		log.Debugf("Querying FirstEntryQuery %.250s", q)
		response, err := s.rsm.FirstEntry(q)
		if err != nil {
			log.Debugf("Querying FirstEntryQuery %.250s failed: %v", q, err)
			query.Output(nil, err)
		} else {
			output, err := proto.Marshal(response)
			if err != nil {
				err = errors.NewInternal(err.Error())
				log.Errorf("Querying FirstEntryQuery %.250s failed: %v", q, err)
				query.Output(nil, err)
			} else {
				log.Debugf("Querying FirstEntryQuery %.250s complete: %+v", q, response)
				query.Output(output, nil)
			}
		}
		query.Close()
	case 5:
		q, err := newLastEntryQuery(query)
		if err != nil {
			err = errors.NewInternal(err.Error())
			log.Error(err)
			query.Output(nil, err)
			return
		}

		log.Debugf("Querying LastEntryQuery %.250s", q)
		response, err := s.rsm.LastEntry(q)
		if err != nil {
			log.Debugf("Querying LastEntryQuery %.250s failed: %v", q, err)
			query.Output(nil, err)
		} else {
			output, err := proto.Marshal(response)
			if err != nil {
				err = errors.NewInternal(err.Error())
				log.Errorf("Querying LastEntryQuery %.250s failed: %v", q, err)
				query.Output(nil, err)
			} else {
				log.Debugf("Querying LastEntryQuery %.250s complete: %+v", q, response)
				query.Output(output, nil)
			}
		}
		query.Close()
	case 6:
		q, err := newPrevEntryQuery(query)
		if err != nil {
			err = errors.NewInternal(err.Error())
			log.Error(err)
			query.Output(nil, err)
			return
		}

		log.Debugf("Querying PrevEntryQuery %.250s", q)
		response, err := s.rsm.PrevEntry(q)
		if err != nil {
			log.Debugf("Querying PrevEntryQuery %.250s failed: %v", q, err)
			query.Output(nil, err)
		} else {
			output, err := proto.Marshal(response)
			if err != nil {
				err = errors.NewInternal(err.Error())
				log.Errorf("Querying PrevEntryQuery %.250s failed: %v", q, err)
				query.Output(nil, err)
			} else {
				log.Debugf("Querying PrevEntryQuery %.250s complete: %+v", q, response)
				query.Output(output, nil)
			}
		}
		query.Close()
	case 7:
		q, err := newNextEntryQuery(query)
		if err != nil {
			err = errors.NewInternal(err.Error())
			log.Error(err)
			query.Output(nil, err)
			return
		}

		log.Debugf("Querying NextEntryQuery %.250s", q)
		response, err := s.rsm.NextEntry(q)
		if err != nil {
			log.Debugf("Querying NextEntryQuery %.250s failed: %v", q, err)
			query.Output(nil, err)
		} else {
			output, err := proto.Marshal(response)
			if err != nil {
				err = errors.NewInternal(err.Error())
				log.Errorf("Querying NextEntryQuery %.250s failed: %v", q, err)
				query.Output(nil, err)
			} else {
				log.Debugf("Querying NextEntryQuery %.250s complete: %+v", q, response)
				query.Output(output, nil)
			}
		}
		query.Close()
	case 11:
		q, err := newEntriesQuery(query)
		if err != nil {
			err = errors.NewInternal(err.Error())
			log.Error(err)
			query.Output(nil, err)
			return
		}

		log.Debugf("Querying EntriesQuery %.250s", q)
		s.rsm.Entries(q)
	default:
		err := errors.NewNotSupported("unknown operation %d", query.OperationID())
		log.Debug(err)
		query.Output(nil, err)
	}
}
func (s *ServiceAdaptor) Backup(writer io.Writer) error {
	err := s.rsm.Backup(newSnapshotWriter(writer))
	if err != nil {
		log.Error(err)
		return err
	}
	return nil
}

func (s *ServiceAdaptor) Restore(reader io.Reader) error {
	err := s.rsm.Restore(newSnapshotReader(reader))
	if err != nil {
		log.Error(err)
		return err
	}
	return nil
}

var _ rsm.Service = &ServiceAdaptor{}
