// Code generated by protoc-gen-go. DO NOT EDIT.
// source: atomix/service/session.proto

package service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Sessionized service snapshot
type SessionizedServiceSnapshot struct {
	Sessions             []*SessionSnapshot `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SessionizedServiceSnapshot) Reset()         { *m = SessionizedServiceSnapshot{} }
func (m *SessionizedServiceSnapshot) String() string { return proto.CompactTextString(m) }
func (*SessionizedServiceSnapshot) ProtoMessage()    {}
func (*SessionizedServiceSnapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_95a8d51c362366b0, []int{0}
}

func (m *SessionizedServiceSnapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionizedServiceSnapshot.Unmarshal(m, b)
}
func (m *SessionizedServiceSnapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionizedServiceSnapshot.Marshal(b, m, deterministic)
}
func (m *SessionizedServiceSnapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionizedServiceSnapshot.Merge(m, src)
}
func (m *SessionizedServiceSnapshot) XXX_Size() int {
	return xxx_messageInfo_SessionizedServiceSnapshot.Size(m)
}
func (m *SessionizedServiceSnapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionizedServiceSnapshot.DiscardUnknown(m)
}

var xxx_messageInfo_SessionizedServiceSnapshot proto.InternalMessageInfo

func (m *SessionizedServiceSnapshot) GetSessions() []*SessionSnapshot {
	if m != nil {
		return m.Sessions
	}
	return nil
}

// Service session
type SessionSnapshot struct {
	SessionId            uint64                   `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Timeout              uint64                   `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Timestamp            uint64                   `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CommandSequence      uint64                   `protobuf:"varint,4,opt,name=command_sequence,json=commandSequence,proto3" json:"command_sequence,omitempty"`
	LastApplied          uint64                   `protobuf:"varint,5,opt,name=last_applied,json=lastApplied,proto3" json:"last_applied,omitempty"`
	Streams              []*SessionStreamSnapshot `protobuf:"bytes,6,rep,name=streams,proto3" json:"streams,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *SessionSnapshot) Reset()         { *m = SessionSnapshot{} }
func (m *SessionSnapshot) String() string { return proto.CompactTextString(m) }
func (*SessionSnapshot) ProtoMessage()    {}
func (*SessionSnapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_95a8d51c362366b0, []int{1}
}

func (m *SessionSnapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionSnapshot.Unmarshal(m, b)
}
func (m *SessionSnapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionSnapshot.Marshal(b, m, deterministic)
}
func (m *SessionSnapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionSnapshot.Merge(m, src)
}
func (m *SessionSnapshot) XXX_Size() int {
	return xxx_messageInfo_SessionSnapshot.Size(m)
}
func (m *SessionSnapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionSnapshot.DiscardUnknown(m)
}

var xxx_messageInfo_SessionSnapshot proto.InternalMessageInfo

func (m *SessionSnapshot) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *SessionSnapshot) GetTimeout() uint64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *SessionSnapshot) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *SessionSnapshot) GetCommandSequence() uint64 {
	if m != nil {
		return m.CommandSequence
	}
	return 0
}

func (m *SessionSnapshot) GetLastApplied() uint64 {
	if m != nil {
		return m.LastApplied
	}
	return 0
}

func (m *SessionSnapshot) GetStreams() []*SessionStreamSnapshot {
	if m != nil {
		return m.Streams
	}
	return nil
}

// Service session stream
type SessionStreamSnapshot struct {
	StreamId             uint64   `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	SequenceNumber       uint64   `protobuf:"varint,3,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	LastCompleted        uint64   `protobuf:"varint,4,opt,name=last_completed,json=lastCompleted,proto3" json:"last_completed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionStreamSnapshot) Reset()         { *m = SessionStreamSnapshot{} }
func (m *SessionStreamSnapshot) String() string { return proto.CompactTextString(m) }
func (*SessionStreamSnapshot) ProtoMessage()    {}
func (*SessionStreamSnapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_95a8d51c362366b0, []int{2}
}

func (m *SessionStreamSnapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionStreamSnapshot.Unmarshal(m, b)
}
func (m *SessionStreamSnapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionStreamSnapshot.Marshal(b, m, deterministic)
}
func (m *SessionStreamSnapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionStreamSnapshot.Merge(m, src)
}
func (m *SessionStreamSnapshot) XXX_Size() int {
	return xxx_messageInfo_SessionStreamSnapshot.Size(m)
}
func (m *SessionStreamSnapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionStreamSnapshot.DiscardUnknown(m)
}

var xxx_messageInfo_SessionStreamSnapshot proto.InternalMessageInfo

func (m *SessionStreamSnapshot) GetStreamId() uint64 {
	if m != nil {
		return m.StreamId
	}
	return 0
}

func (m *SessionStreamSnapshot) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SessionStreamSnapshot) GetSequenceNumber() uint64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *SessionStreamSnapshot) GetLastCompleted() uint64 {
	if m != nil {
		return m.LastCompleted
	}
	return 0
}

type SessionRequest struct {
	// Types that are valid to be assigned to Request:
	//	*SessionRequest_OpenSession
	//	*SessionRequest_KeepAlive
	//	*SessionRequest_CloseSession
	//	*SessionRequest_Command
	//	*SessionRequest_Query
	Request              isSessionRequest_Request `protobuf_oneof:"request"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *SessionRequest) Reset()         { *m = SessionRequest{} }
func (m *SessionRequest) String() string { return proto.CompactTextString(m) }
func (*SessionRequest) ProtoMessage()    {}
func (*SessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_95a8d51c362366b0, []int{3}
}

func (m *SessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionRequest.Unmarshal(m, b)
}
func (m *SessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionRequest.Marshal(b, m, deterministic)
}
func (m *SessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionRequest.Merge(m, src)
}
func (m *SessionRequest) XXX_Size() int {
	return xxx_messageInfo_SessionRequest.Size(m)
}
func (m *SessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SessionRequest proto.InternalMessageInfo

type isSessionRequest_Request interface {
	isSessionRequest_Request()
}

type SessionRequest_OpenSession struct {
	OpenSession *OpenSessionRequest `protobuf:"bytes,1,opt,name=open_session,json=openSession,proto3,oneof"`
}

type SessionRequest_KeepAlive struct {
	KeepAlive *KeepAliveRequest `protobuf:"bytes,2,opt,name=keep_alive,json=keepAlive,proto3,oneof"`
}

type SessionRequest_CloseSession struct {
	CloseSession *CloseSessionRequest `protobuf:"bytes,3,opt,name=close_session,json=closeSession,proto3,oneof"`
}

type SessionRequest_Command struct {
	Command *SessionCommandRequest `protobuf:"bytes,4,opt,name=command,proto3,oneof"`
}

type SessionRequest_Query struct {
	Query *SessionQueryRequest `protobuf:"bytes,5,opt,name=query,proto3,oneof"`
}

func (*SessionRequest_OpenSession) isSessionRequest_Request() {}

func (*SessionRequest_KeepAlive) isSessionRequest_Request() {}

func (*SessionRequest_CloseSession) isSessionRequest_Request() {}

func (*SessionRequest_Command) isSessionRequest_Request() {}

func (*SessionRequest_Query) isSessionRequest_Request() {}

func (m *SessionRequest) GetRequest() isSessionRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *SessionRequest) GetOpenSession() *OpenSessionRequest {
	if x, ok := m.GetRequest().(*SessionRequest_OpenSession); ok {
		return x.OpenSession
	}
	return nil
}

func (m *SessionRequest) GetKeepAlive() *KeepAliveRequest {
	if x, ok := m.GetRequest().(*SessionRequest_KeepAlive); ok {
		return x.KeepAlive
	}
	return nil
}

func (m *SessionRequest) GetCloseSession() *CloseSessionRequest {
	if x, ok := m.GetRequest().(*SessionRequest_CloseSession); ok {
		return x.CloseSession
	}
	return nil
}

func (m *SessionRequest) GetCommand() *SessionCommandRequest {
	if x, ok := m.GetRequest().(*SessionRequest_Command); ok {
		return x.Command
	}
	return nil
}

func (m *SessionRequest) GetQuery() *SessionQueryRequest {
	if x, ok := m.GetRequest().(*SessionRequest_Query); ok {
		return x.Query
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SessionRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SessionRequest_OpenSession)(nil),
		(*SessionRequest_KeepAlive)(nil),
		(*SessionRequest_CloseSession)(nil),
		(*SessionRequest_Command)(nil),
		(*SessionRequest_Query)(nil),
	}
}

type SessionResponse struct {
	// Types that are valid to be assigned to Response:
	//	*SessionResponse_OpenSession
	//	*SessionResponse_KeepAlive
	//	*SessionResponse_CloseSession
	//	*SessionResponse_Command
	//	*SessionResponse_Query
	Response             isSessionResponse_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *SessionResponse) Reset()         { *m = SessionResponse{} }
func (m *SessionResponse) String() string { return proto.CompactTextString(m) }
func (*SessionResponse) ProtoMessage()    {}
func (*SessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_95a8d51c362366b0, []int{4}
}

func (m *SessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionResponse.Unmarshal(m, b)
}
func (m *SessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionResponse.Marshal(b, m, deterministic)
}
func (m *SessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionResponse.Merge(m, src)
}
func (m *SessionResponse) XXX_Size() int {
	return xxx_messageInfo_SessionResponse.Size(m)
}
func (m *SessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SessionResponse proto.InternalMessageInfo

type isSessionResponse_Response interface {
	isSessionResponse_Response()
}

type SessionResponse_OpenSession struct {
	OpenSession *OpenSessionResponse `protobuf:"bytes,1,opt,name=open_session,json=openSession,proto3,oneof"`
}

type SessionResponse_KeepAlive struct {
	KeepAlive *KeepAliveResponse `protobuf:"bytes,2,opt,name=keep_alive,json=keepAlive,proto3,oneof"`
}

type SessionResponse_CloseSession struct {
	CloseSession *CloseSessionResponse `protobuf:"bytes,3,opt,name=close_session,json=closeSession,proto3,oneof"`
}

type SessionResponse_Command struct {
	Command *SessionCommandResponse `protobuf:"bytes,4,opt,name=command,proto3,oneof"`
}

type SessionResponse_Query struct {
	Query *SessionQueryResponse `protobuf:"bytes,5,opt,name=query,proto3,oneof"`
}

func (*SessionResponse_OpenSession) isSessionResponse_Response() {}

func (*SessionResponse_KeepAlive) isSessionResponse_Response() {}

func (*SessionResponse_CloseSession) isSessionResponse_Response() {}

func (*SessionResponse_Command) isSessionResponse_Response() {}

func (*SessionResponse_Query) isSessionResponse_Response() {}

func (m *SessionResponse) GetResponse() isSessionResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *SessionResponse) GetOpenSession() *OpenSessionResponse {
	if x, ok := m.GetResponse().(*SessionResponse_OpenSession); ok {
		return x.OpenSession
	}
	return nil
}

func (m *SessionResponse) GetKeepAlive() *KeepAliveResponse {
	if x, ok := m.GetResponse().(*SessionResponse_KeepAlive); ok {
		return x.KeepAlive
	}
	return nil
}

func (m *SessionResponse) GetCloseSession() *CloseSessionResponse {
	if x, ok := m.GetResponse().(*SessionResponse_CloseSession); ok {
		return x.CloseSession
	}
	return nil
}

func (m *SessionResponse) GetCommand() *SessionCommandResponse {
	if x, ok := m.GetResponse().(*SessionResponse_Command); ok {
		return x.Command
	}
	return nil
}

func (m *SessionResponse) GetQuery() *SessionQueryResponse {
	if x, ok := m.GetResponse().(*SessionResponse_Query); ok {
		return x.Query
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SessionResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SessionResponse_OpenSession)(nil),
		(*SessionResponse_KeepAlive)(nil),
		(*SessionResponse_CloseSession)(nil),
		(*SessionResponse_Command)(nil),
		(*SessionResponse_Query)(nil),
	}
}

type OpenSessionRequest struct {
	Timeout              int64    `protobuf:"varint,1,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenSessionRequest) Reset()         { *m = OpenSessionRequest{} }
func (m *OpenSessionRequest) String() string { return proto.CompactTextString(m) }
func (*OpenSessionRequest) ProtoMessage()    {}
func (*OpenSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_95a8d51c362366b0, []int{5}
}

func (m *OpenSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenSessionRequest.Unmarshal(m, b)
}
func (m *OpenSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenSessionRequest.Marshal(b, m, deterministic)
}
func (m *OpenSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenSessionRequest.Merge(m, src)
}
func (m *OpenSessionRequest) XXX_Size() int {
	return xxx_messageInfo_OpenSessionRequest.Size(m)
}
func (m *OpenSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OpenSessionRequest proto.InternalMessageInfo

func (m *OpenSessionRequest) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

type OpenSessionResponse struct {
	SessionId            uint64   `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenSessionResponse) Reset()         { *m = OpenSessionResponse{} }
func (m *OpenSessionResponse) String() string { return proto.CompactTextString(m) }
func (*OpenSessionResponse) ProtoMessage()    {}
func (*OpenSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_95a8d51c362366b0, []int{6}
}

func (m *OpenSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenSessionResponse.Unmarshal(m, b)
}
func (m *OpenSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenSessionResponse.Marshal(b, m, deterministic)
}
func (m *OpenSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenSessionResponse.Merge(m, src)
}
func (m *OpenSessionResponse) XXX_Size() int {
	return xxx_messageInfo_OpenSessionResponse.Size(m)
}
func (m *OpenSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OpenSessionResponse proto.InternalMessageInfo

func (m *OpenSessionResponse) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

type KeepAliveRequest struct {
	SessionId            uint64            `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CommandSequence      uint64            `protobuf:"varint,2,opt,name=command_sequence,json=commandSequence,proto3" json:"command_sequence,omitempty"`
	Streams              map[uint64]uint64 `protobuf:"bytes,3,rep,name=streams,proto3" json:"streams,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *KeepAliveRequest) Reset()         { *m = KeepAliveRequest{} }
func (m *KeepAliveRequest) String() string { return proto.CompactTextString(m) }
func (*KeepAliveRequest) ProtoMessage()    {}
func (*KeepAliveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_95a8d51c362366b0, []int{7}
}

func (m *KeepAliveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeepAliveRequest.Unmarshal(m, b)
}
func (m *KeepAliveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeepAliveRequest.Marshal(b, m, deterministic)
}
func (m *KeepAliveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeepAliveRequest.Merge(m, src)
}
func (m *KeepAliveRequest) XXX_Size() int {
	return xxx_messageInfo_KeepAliveRequest.Size(m)
}
func (m *KeepAliveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KeepAliveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KeepAliveRequest proto.InternalMessageInfo

func (m *KeepAliveRequest) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *KeepAliveRequest) GetCommandSequence() uint64 {
	if m != nil {
		return m.CommandSequence
	}
	return 0
}

func (m *KeepAliveRequest) GetStreams() map[uint64]uint64 {
	if m != nil {
		return m.Streams
	}
	return nil
}

type KeepAliveResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeepAliveResponse) Reset()         { *m = KeepAliveResponse{} }
func (m *KeepAliveResponse) String() string { return proto.CompactTextString(m) }
func (*KeepAliveResponse) ProtoMessage()    {}
func (*KeepAliveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_95a8d51c362366b0, []int{8}
}

func (m *KeepAliveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeepAliveResponse.Unmarshal(m, b)
}
func (m *KeepAliveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeepAliveResponse.Marshal(b, m, deterministic)
}
func (m *KeepAliveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeepAliveResponse.Merge(m, src)
}
func (m *KeepAliveResponse) XXX_Size() int {
	return xxx_messageInfo_KeepAliveResponse.Size(m)
}
func (m *KeepAliveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KeepAliveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KeepAliveResponse proto.InternalMessageInfo

type CloseSessionRequest struct {
	SessionId            uint64   `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseSessionRequest) Reset()         { *m = CloseSessionRequest{} }
func (m *CloseSessionRequest) String() string { return proto.CompactTextString(m) }
func (*CloseSessionRequest) ProtoMessage()    {}
func (*CloseSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_95a8d51c362366b0, []int{9}
}

func (m *CloseSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseSessionRequest.Unmarshal(m, b)
}
func (m *CloseSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseSessionRequest.Marshal(b, m, deterministic)
}
func (m *CloseSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseSessionRequest.Merge(m, src)
}
func (m *CloseSessionRequest) XXX_Size() int {
	return xxx_messageInfo_CloseSessionRequest.Size(m)
}
func (m *CloseSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CloseSessionRequest proto.InternalMessageInfo

func (m *CloseSessionRequest) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

type CloseSessionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseSessionResponse) Reset()         { *m = CloseSessionResponse{} }
func (m *CloseSessionResponse) String() string { return proto.CompactTextString(m) }
func (*CloseSessionResponse) ProtoMessage()    {}
func (*CloseSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_95a8d51c362366b0, []int{10}
}

func (m *CloseSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseSessionResponse.Unmarshal(m, b)
}
func (m *CloseSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseSessionResponse.Marshal(b, m, deterministic)
}
func (m *CloseSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseSessionResponse.Merge(m, src)
}
func (m *CloseSessionResponse) XXX_Size() int {
	return xxx_messageInfo_CloseSessionResponse.Size(m)
}
func (m *CloseSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CloseSessionResponse proto.InternalMessageInfo

type SessionCommandRequest struct {
	Context              *SessionCommandContext `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Input                []byte                 `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SessionCommandRequest) Reset()         { *m = SessionCommandRequest{} }
func (m *SessionCommandRequest) String() string { return proto.CompactTextString(m) }
func (*SessionCommandRequest) ProtoMessage()    {}
func (*SessionCommandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_95a8d51c362366b0, []int{11}
}

func (m *SessionCommandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionCommandRequest.Unmarshal(m, b)
}
func (m *SessionCommandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionCommandRequest.Marshal(b, m, deterministic)
}
func (m *SessionCommandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionCommandRequest.Merge(m, src)
}
func (m *SessionCommandRequest) XXX_Size() int {
	return xxx_messageInfo_SessionCommandRequest.Size(m)
}
func (m *SessionCommandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionCommandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SessionCommandRequest proto.InternalMessageInfo

func (m *SessionCommandRequest) GetContext() *SessionCommandContext {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *SessionCommandRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SessionCommandRequest) GetInput() []byte {
	if m != nil {
		return m.Input
	}
	return nil
}

type SessionCommandResponse struct {
	Context              *SessionResponseContext `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Output               []byte                  `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *SessionCommandResponse) Reset()         { *m = SessionCommandResponse{} }
func (m *SessionCommandResponse) String() string { return proto.CompactTextString(m) }
func (*SessionCommandResponse) ProtoMessage()    {}
func (*SessionCommandResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_95a8d51c362366b0, []int{12}
}

func (m *SessionCommandResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionCommandResponse.Unmarshal(m, b)
}
func (m *SessionCommandResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionCommandResponse.Marshal(b, m, deterministic)
}
func (m *SessionCommandResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionCommandResponse.Merge(m, src)
}
func (m *SessionCommandResponse) XXX_Size() int {
	return xxx_messageInfo_SessionCommandResponse.Size(m)
}
func (m *SessionCommandResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionCommandResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SessionCommandResponse proto.InternalMessageInfo

func (m *SessionCommandResponse) GetContext() *SessionResponseContext {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *SessionCommandResponse) GetOutput() []byte {
	if m != nil {
		return m.Output
	}
	return nil
}

type SessionQueryRequest struct {
	Context              *SessionQueryContext `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Input                []byte               `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SessionQueryRequest) Reset()         { *m = SessionQueryRequest{} }
func (m *SessionQueryRequest) String() string { return proto.CompactTextString(m) }
func (*SessionQueryRequest) ProtoMessage()    {}
func (*SessionQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_95a8d51c362366b0, []int{13}
}

func (m *SessionQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionQueryRequest.Unmarshal(m, b)
}
func (m *SessionQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionQueryRequest.Marshal(b, m, deterministic)
}
func (m *SessionQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionQueryRequest.Merge(m, src)
}
func (m *SessionQueryRequest) XXX_Size() int {
	return xxx_messageInfo_SessionQueryRequest.Size(m)
}
func (m *SessionQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SessionQueryRequest proto.InternalMessageInfo

func (m *SessionQueryRequest) GetContext() *SessionQueryContext {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *SessionQueryRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SessionQueryRequest) GetInput() []byte {
	if m != nil {
		return m.Input
	}
	return nil
}

type SessionQueryResponse struct {
	Context              *SessionResponseContext `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Output               []byte                  `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *SessionQueryResponse) Reset()         { *m = SessionQueryResponse{} }
func (m *SessionQueryResponse) String() string { return proto.CompactTextString(m) }
func (*SessionQueryResponse) ProtoMessage()    {}
func (*SessionQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_95a8d51c362366b0, []int{14}
}

func (m *SessionQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionQueryResponse.Unmarshal(m, b)
}
func (m *SessionQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionQueryResponse.Marshal(b, m, deterministic)
}
func (m *SessionQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionQueryResponse.Merge(m, src)
}
func (m *SessionQueryResponse) XXX_Size() int {
	return xxx_messageInfo_SessionQueryResponse.Size(m)
}
func (m *SessionQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SessionQueryResponse proto.InternalMessageInfo

func (m *SessionQueryResponse) GetContext() *SessionResponseContext {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *SessionQueryResponse) GetOutput() []byte {
	if m != nil {
		return m.Output
	}
	return nil
}

type SessionCommandContext struct {
	SessionId            uint64   `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SequenceNumber       uint64   `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionCommandContext) Reset()         { *m = SessionCommandContext{} }
func (m *SessionCommandContext) String() string { return proto.CompactTextString(m) }
func (*SessionCommandContext) ProtoMessage()    {}
func (*SessionCommandContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_95a8d51c362366b0, []int{15}
}

func (m *SessionCommandContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionCommandContext.Unmarshal(m, b)
}
func (m *SessionCommandContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionCommandContext.Marshal(b, m, deterministic)
}
func (m *SessionCommandContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionCommandContext.Merge(m, src)
}
func (m *SessionCommandContext) XXX_Size() int {
	return xxx_messageInfo_SessionCommandContext.Size(m)
}
func (m *SessionCommandContext) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionCommandContext.DiscardUnknown(m)
}

var xxx_messageInfo_SessionCommandContext proto.InternalMessageInfo

func (m *SessionCommandContext) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *SessionCommandContext) GetSequenceNumber() uint64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

type SessionQueryContext struct {
	SessionId            uint64   `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	LastSequenceNumber   uint64   `protobuf:"varint,2,opt,name=last_sequence_number,json=lastSequenceNumber,proto3" json:"last_sequence_number,omitempty"`
	LastIndex            uint64   `protobuf:"varint,3,opt,name=last_index,json=lastIndex,proto3" json:"last_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionQueryContext) Reset()         { *m = SessionQueryContext{} }
func (m *SessionQueryContext) String() string { return proto.CompactTextString(m) }
func (*SessionQueryContext) ProtoMessage()    {}
func (*SessionQueryContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_95a8d51c362366b0, []int{16}
}

func (m *SessionQueryContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionQueryContext.Unmarshal(m, b)
}
func (m *SessionQueryContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionQueryContext.Marshal(b, m, deterministic)
}
func (m *SessionQueryContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionQueryContext.Merge(m, src)
}
func (m *SessionQueryContext) XXX_Size() int {
	return xxx_messageInfo_SessionQueryContext.Size(m)
}
func (m *SessionQueryContext) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionQueryContext.DiscardUnknown(m)
}

var xxx_messageInfo_SessionQueryContext proto.InternalMessageInfo

func (m *SessionQueryContext) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *SessionQueryContext) GetLastSequenceNumber() uint64 {
	if m != nil {
		return m.LastSequenceNumber
	}
	return 0
}

func (m *SessionQueryContext) GetLastIndex() uint64 {
	if m != nil {
		return m.LastIndex
	}
	return 0
}

type SessionResponseContext struct {
	StreamId             uint64   `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Index                uint64   `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Sequence             uint64   `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionResponseContext) Reset()         { *m = SessionResponseContext{} }
func (m *SessionResponseContext) String() string { return proto.CompactTextString(m) }
func (*SessionResponseContext) ProtoMessage()    {}
func (*SessionResponseContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_95a8d51c362366b0, []int{17}
}

func (m *SessionResponseContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionResponseContext.Unmarshal(m, b)
}
func (m *SessionResponseContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionResponseContext.Marshal(b, m, deterministic)
}
func (m *SessionResponseContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionResponseContext.Merge(m, src)
}
func (m *SessionResponseContext) XXX_Size() int {
	return xxx_messageInfo_SessionResponseContext.Size(m)
}
func (m *SessionResponseContext) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionResponseContext.DiscardUnknown(m)
}

var xxx_messageInfo_SessionResponseContext proto.InternalMessageInfo

func (m *SessionResponseContext) GetStreamId() uint64 {
	if m != nil {
		return m.StreamId
	}
	return 0
}

func (m *SessionResponseContext) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *SessionResponseContext) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

type PrimitiveEvent struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimitiveEvent) Reset()         { *m = PrimitiveEvent{} }
func (m *PrimitiveEvent) String() string { return proto.CompactTextString(m) }
func (*PrimitiveEvent) ProtoMessage()    {}
func (*PrimitiveEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_95a8d51c362366b0, []int{18}
}

func (m *PrimitiveEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimitiveEvent.Unmarshal(m, b)
}
func (m *PrimitiveEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimitiveEvent.Marshal(b, m, deterministic)
}
func (m *PrimitiveEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimitiveEvent.Merge(m, src)
}
func (m *PrimitiveEvent) XXX_Size() int {
	return xxx_messageInfo_PrimitiveEvent.Size(m)
}
func (m *PrimitiveEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimitiveEvent.DiscardUnknown(m)
}

var xxx_messageInfo_PrimitiveEvent proto.InternalMessageInfo

func (m *PrimitiveEvent) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *PrimitiveEvent) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*SessionizedServiceSnapshot)(nil), "atomix.service.SessionizedServiceSnapshot")
	proto.RegisterType((*SessionSnapshot)(nil), "atomix.service.SessionSnapshot")
	proto.RegisterType((*SessionStreamSnapshot)(nil), "atomix.service.SessionStreamSnapshot")
	proto.RegisterType((*SessionRequest)(nil), "atomix.service.SessionRequest")
	proto.RegisterType((*SessionResponse)(nil), "atomix.service.SessionResponse")
	proto.RegisterType((*OpenSessionRequest)(nil), "atomix.service.OpenSessionRequest")
	proto.RegisterType((*OpenSessionResponse)(nil), "atomix.service.OpenSessionResponse")
	proto.RegisterType((*KeepAliveRequest)(nil), "atomix.service.KeepAliveRequest")
	proto.RegisterMapType((map[uint64]uint64)(nil), "atomix.service.KeepAliveRequest.StreamsEntry")
	proto.RegisterType((*KeepAliveResponse)(nil), "atomix.service.KeepAliveResponse")
	proto.RegisterType((*CloseSessionRequest)(nil), "atomix.service.CloseSessionRequest")
	proto.RegisterType((*CloseSessionResponse)(nil), "atomix.service.CloseSessionResponse")
	proto.RegisterType((*SessionCommandRequest)(nil), "atomix.service.SessionCommandRequest")
	proto.RegisterType((*SessionCommandResponse)(nil), "atomix.service.SessionCommandResponse")
	proto.RegisterType((*SessionQueryRequest)(nil), "atomix.service.SessionQueryRequest")
	proto.RegisterType((*SessionQueryResponse)(nil), "atomix.service.SessionQueryResponse")
	proto.RegisterType((*SessionCommandContext)(nil), "atomix.service.SessionCommandContext")
	proto.RegisterType((*SessionQueryContext)(nil), "atomix.service.SessionQueryContext")
	proto.RegisterType((*SessionResponseContext)(nil), "atomix.service.SessionResponseContext")
	proto.RegisterType((*PrimitiveEvent)(nil), "atomix.service.PrimitiveEvent")
}

func init() { proto.RegisterFile("atomix/service/session.proto", fileDescriptor_95a8d51c362366b0) }

var fileDescriptor_95a8d51c362366b0 = []byte{
	// 840 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xcd, 0x4e, 0x1b, 0x49,
	0x10, 0xde, 0xb1, 0x01, 0xe3, 0xb2, 0x31, 0x6c, 0xe3, 0x45, 0x23, 0x16, 0xb4, 0xd0, 0xc0, 0x2e,
	0x7b, 0x88, 0x89, 0x48, 0x0e, 0x11, 0x24, 0x4a, 0x8c, 0x85, 0x80, 0x20, 0xe5, 0x67, 0x7c, 0xca,
	0xc9, 0x1a, 0x3c, 0xad, 0x64, 0x84, 0xe7, 0x87, 0xe9, 0xb6, 0x85, 0x73, 0xc8, 0x21, 0x52, 0xde,
	0x21, 0xaf, 0x97, 0x67, 0xc8, 0x21, 0x52, 0x4e, 0x51, 0xff, 0x4c, 0xdb, 0x33, 0x6e, 0xec, 0x48,
	0x51, 0x6e, 0xd3, 0x5f, 0x57, 0xd5, 0x54, 0x7d, 0x5d, 0xf5, 0x75, 0xc3, 0x86, 0xcb, 0xa2, 0xc0,
	0xbf, 0x3d, 0xa0, 0x24, 0x19, 0xf8, 0x5d, 0x72, 0x40, 0x09, 0xa5, 0x7e, 0x14, 0x36, 0xe2, 0x24,
	0x62, 0x11, 0xaa, 0xc9, 0xdd, 0x86, 0xda, 0xc5, 0x6f, 0x60, 0xbd, 0x2d, 0x0d, 0xfc, 0xf7, 0xc4,
	0x6b, 0x4b, 0xb4, 0x1d, 0xba, 0x31, 0x7d, 0x17, 0x31, 0x74, 0x0c, 0x8b, 0xca, 0x9d, 0xda, 0xd6,
	0x56, 0x71, 0xbf, 0x72, 0xf8, 0x4f, 0x23, 0x1b, 0xa0, 0xa1, 0xbc, 0x53, 0x17, 0x47, 0x3b, 0xe0,
	0x6f, 0x16, 0x2c, 0xe7, 0x76, 0xd1, 0x26, 0x80, 0xda, 0xef, 0xf8, 0x9e, 0x6d, 0x6d, 0x59, 0xfb,
	0x73, 0x4e, 0x59, 0x21, 0x17, 0x1e, 0xb2, 0xa1, 0xc4, 0xfc, 0x80, 0x44, 0x7d, 0x66, 0x17, 0xc4,
	0x5e, 0xba, 0x44, 0x1b, 0x50, 0xe6, 0x9f, 0x94, 0xb9, 0x41, 0x6c, 0x17, 0xa5, 0x9f, 0x06, 0xd0,
	0xff, 0xb0, 0xd2, 0x8d, 0x82, 0xc0, 0x0d, 0xbd, 0x0e, 0x25, 0x37, 0x7d, 0x12, 0x76, 0x89, 0x3d,
	0x27, 0x8c, 0x96, 0x15, 0xde, 0x56, 0x30, 0xda, 0x86, 0x6a, 0xcf, 0xa5, 0xac, 0xe3, 0xc6, 0x71,
	0xcf, 0x27, 0x9e, 0x3d, 0x2f, 0xcc, 0x2a, 0x1c, 0x6b, 0x4a, 0x08, 0x3d, 0x85, 0x12, 0x65, 0x09,
	0x71, 0x03, 0x6a, 0x2f, 0x88, 0xa2, 0xf7, 0xee, 0x2a, 0x5a, 0x58, 0xe9, 0xd2, 0x53, 0x2f, 0xfc,
	0xd9, 0x82, 0xbf, 0x8c, 0x26, 0xe8, 0x6f, 0x28, 0x4b, 0xa3, 0x51, 0xf9, 0x8b, 0x12, 0xb8, 0xf0,
	0x10, 0x82, 0x39, 0x36, 0x8c, 0x89, 0x28, 0xbd, 0xec, 0x88, 0x6f, 0xf4, 0x1f, 0x2c, 0xa7, 0x15,
	0x75, 0xc2, 0x7e, 0x70, 0x45, 0x12, 0x55, 0x7d, 0x2d, 0x85, 0x5f, 0x08, 0x14, 0xed, 0x41, 0x4d,
	0xd4, 0xd5, 0x8d, 0x82, 0xb8, 0x47, 0x18, 0xf1, 0x14, 0x01, 0x4b, 0x1c, 0x6d, 0xa5, 0x20, 0xfe,
	0x5a, 0x80, 0x9a, 0x4a, 0xcd, 0xe1, 0x01, 0x28, 0x43, 0x67, 0x50, 0x8d, 0x62, 0x12, 0x76, 0xd4,
	0x31, 0x88, 0xb4, 0x2a, 0x87, 0x38, 0x5f, 0xf3, 0xcb, 0x98, 0x84, 0x59, 0xcf, 0xf3, 0x3f, 0x9c,
	0x4a, 0x34, 0x42, 0x51, 0x13, 0xe0, 0x9a, 0x90, 0xb8, 0xe3, 0xf6, 0xfc, 0x81, 0xac, 0xa2, 0x72,
	0xb8, 0x95, 0x0f, 0x73, 0x49, 0x48, 0xdc, 0xe4, 0x06, 0xa3, 0x20, 0xe5, 0xeb, 0x14, 0x43, 0xcf,
	0x61, 0xa9, 0xdb, 0x8b, 0x28, 0xd1, 0xc9, 0x14, 0x45, 0x94, 0x9d, 0x7c, 0x94, 0x16, 0x37, 0x9a,
	0xc8, 0xa6, 0xda, 0x1d, 0x83, 0x51, 0x13, 0x4a, 0xea, 0xf0, 0x05, 0x15, 0x77, 0x1f, 0x63, 0x4b,
	0x5a, 0x8d, 0xe2, 0xa4, 0x7e, 0xe8, 0x18, 0xe6, 0x6f, 0xfa, 0x24, 0x19, 0x8a, 0x2e, 0x31, 0xa4,
	0xa1, 0x02, 0xbc, 0xe6, 0x36, 0x23, 0x77, 0xe9, 0x73, 0x52, 0x86, 0x52, 0x22, 0x31, 0xfc, 0xbd,
	0xa0, 0x47, 0xc1, 0x21, 0x34, 0x8e, 0x42, 0x4a, 0xd0, 0xb9, 0x91, 0xf6, 0x9d, 0xa9, 0xb4, 0x4b,
	0xd7, 0x3c, 0xef, 0x27, 0x06, 0xde, 0xb7, 0xa7, 0xf0, 0xae, 0xa3, 0x8c, 0x11, 0x7f, 0x69, 0x26,
	0x7e, 0x77, 0x3a, 0xf1, 0x3a, 0x52, 0x96, 0xf9, 0x93, 0x3c, 0xf3, 0xff, 0xce, 0x62, 0x5e, 0x07,
	0xd2, 0xd4, 0x3f, 0xce, 0x52, 0xbf, 0x3b, 0x9d, 0x7a, 0xed, 0xaf, 0xb8, 0x07, 0x58, 0x4c, 0x14,
	0x88, 0x1b, 0x80, 0x26, 0x7b, 0x77, 0x5c, 0x6a, 0x38, 0xf3, 0x45, 0x2d, 0x35, 0xf8, 0x21, 0xac,
	0x1a, 0x48, 0x9f, 0x21, 0x5d, 0xf8, 0x8b, 0x05, 0x2b, 0xf9, 0xde, 0x9e, 0x25, 0x77, 0x26, 0xd9,
	0x2a, 0x98, 0x65, 0xeb, 0x6c, 0xa4, 0x49, 0x45, 0xa1, 0x49, 0xf7, 0x66, 0x0d, 0x56, 0x43, 0x4a,
	0x0f, 0x3d, 0x0d, 0x59, 0x32, 0xd4, 0xda, 0xb4, 0x7e, 0x04, 0xd5, 0xf1, 0x0d, 0xb4, 0x02, 0xc5,
	0x6b, 0x32, 0x54, 0xb9, 0xf1, 0x4f, 0x54, 0x87, 0xf9, 0x81, 0xdb, 0xeb, 0xa7, 0xa9, 0xc8, 0xc5,
	0x51, 0xe1, 0x91, 0x85, 0x57, 0xe1, 0xcf, 0x89, 0x36, 0xe2, 0x74, 0x19, 0xa6, 0x71, 0x16, 0x5d,
	0x6b, 0x50, 0x37, 0xb5, 0x12, 0xfe, 0x38, 0x92, 0xce, 0xec, 0x58, 0x72, 0x55, 0xee, 0x46, 0x21,
	0x23, 0xb7, 0x4c, 0x8d, 0xca, 0x8c, 0x71, 0x6e, 0x49, 0x63, 0x27, 0xf5, 0xe2, 0xf2, 0x1a, 0xba,
	0x81, 0x96, 0x57, 0xfe, 0xcd, 0x6b, 0xf5, 0xc3, 0xb8, 0xcf, 0x44, 0xbb, 0x57, 0x1d, 0xb9, 0xc0,
	0x09, 0xac, 0x99, 0x1b, 0x14, 0x3d, 0xcb, 0x27, 0x71, 0x57, 0x67, 0xa7, 0x1e, 0x13, 0x59, 0xac,
	0xc1, 0x42, 0xd4, 0x67, 0xb1, 0xba, 0xe1, 0xaa, 0x8e, 0x5a, 0xe1, 0x0f, 0xb0, 0x6a, 0x50, 0x13,
	0xf4, 0x24, 0xff, 0xc3, 0xa9, 0x1a, 0xf4, 0x0b, 0x35, 0xc7, 0x50, 0x37, 0x8d, 0xd4, 0x6f, 0xac,
	0xb8, 0x93, 0x3f, 0x69, 0xe5, 0x39, 0x6b, 0x6a, 0x0c, 0x57, 0x62, 0xc1, 0x74, 0x25, 0xe2, 0x4f,
	0x56, 0x96, 0xd3, 0x9f, 0x8c, 0x7f, 0x1f, 0xea, 0xe2, 0x26, 0x35, 0xff, 0x04, 0xf1, 0xbd, 0x76,
	0xf6, 0xee, 0xdd, 0x04, 0x10, 0x1e, 0x7e, 0xe8, 0x91, 0xdb, 0xf4, 0x75, 0xc2, 0x91, 0x0b, 0x0e,
	0xe0, 0xb7, 0xba, 0x9d, 0x72, 0x1c, 0x4d, 0x7f, 0x0e, 0x88, 0x73, 0xe2, 0x01, 0xd5, 0x1c, 0x8a,
	0x05, 0x5a, 0xe7, 0x4f, 0x32, 0xa5, 0x15, 0x45, 0xe5, 0xa1, 0xd6, 0xf8, 0x08, 0x6a, 0xaf, 0x12,
	0x3f, 0xf0, 0x99, 0x3f, 0x20, 0xa7, 0x03, 0x12, 0x32, 0xfd, 0xa4, 0xb0, 0xc6, 0x9e, 0x14, 0x99,
	0xf9, 0xae, 0xaa, 0xf9, 0xbe, 0x5a, 0x10, 0xef, 0xc3, 0x07, 0x3f, 0x02, 0x00, 0x00, 0xff, 0xff,
	0xb9, 0xeb, 0xf6, 0xa7, 0x3f, 0x0a, 0x00, 0x00,
}
