// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: atomix/storage/protocol/gossip/value/state.proto

package value

import (
	fmt "fmt"
	meta "github.com/atomix/atomix-api/go/atomix/primitive/meta"
	_ "github.com/atomix/atomix-go-framework/pkg/atomix/storage/protocol/gossip/primitive"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ValueState struct {
	meta.ObjectMeta `protobuf:"bytes,1,opt,name=meta,proto3,embedded=meta" json:"meta"`
	Value           []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *ValueState) Reset()         { *m = ValueState{} }
func (m *ValueState) String() string { return proto.CompactTextString(m) }
func (*ValueState) ProtoMessage()    {}
func (*ValueState) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6dd4a1b8e2360f, []int{0}
}
func (m *ValueState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValueState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ValueState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ValueState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValueState.Merge(m, src)
}
func (m *ValueState) XXX_Size() int {
	return m.Size()
}
func (m *ValueState) XXX_DiscardUnknown() {
	xxx_messageInfo_ValueState.DiscardUnknown(m)
}

var xxx_messageInfo_ValueState proto.InternalMessageInfo

func (m *ValueState) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*ValueState)(nil), "atomix.storage.protocol.gossip.value.ValueState")
}

func init() {
	proto.RegisterFile("atomix/storage/protocol/gossip/value/state.proto", fileDescriptor_5c6dd4a1b8e2360f)
}

var fileDescriptor_5c6dd4a1b8e2360f = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0xcf, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x06, 0xe0, 0x18, 0x01, 0x83, 0xe9, 0x14, 0x75, 0x88, 0x3a, 0xb8, 0xa5, 0x62, 0xc8, 0xe4,
	0x43, 0x30, 0xb1, 0x96, 0x19, 0x21, 0x15, 0x89, 0xdd, 0xad, 0x4e, 0x96, 0x51, 0xd3, 0x8b, 0xe2,
	0xa3, 0xea, 0x0b, 0x20, 0x31, 0xf2, 0x58, 0x1d, 0x33, 0x32, 0x55, 0x28, 0x79, 0x11, 0x64, 0x3b,
	0xc0, 0xc8, 0x76, 0xc9, 0xe9, 0xbb, 0xff, 0xb7, 0xbc, 0x36, 0x4c, 0x95, 0xdb, 0x83, 0x67, 0x6a,
	0x8c, 0x45, 0xa8, 0x1b, 0x62, 0x5a, 0xd3, 0x06, 0x2c, 0x79, 0xef, 0x6a, 0xd8, 0x99, 0xcd, 0x2b,
	0x82, 0x67, 0xc3, 0xa8, 0xe3, 0x2e, 0xbf, 0x4a, 0x42, 0x0f, 0x42, 0xff, 0x08, 0x9d, 0x84, 0x8e,
	0x62, 0x32, 0x1f, 0xee, 0xd6, 0x8d, 0xab, 0x1c, 0xbb, 0x1d, 0x42, 0x85, 0x6c, 0x80, 0x56, 0x2f,
	0xb8, 0xe6, 0x64, 0x26, 0x77, 0xff, 0x64, 0xff, 0x59, 0xdc, 0x33, 0x6e, 0xbd, 0xa3, 0xad, 0x1f,
	0xe8, 0xd8, 0x92, 0xa5, 0x38, 0x42, 0x98, 0xd2, 0xdf, 0xb9, 0x95, 0xf2, 0x39, 0xa4, 0x3f, 0x85,
	0xba, 0xf9, 0xbd, 0x3c, 0x0d, 0x99, 0x85, 0x98, 0x89, 0xf2, 0xe2, 0xe6, 0x52, 0x0f, 0xbd, 0x7f,
	0xaf, 0xea, 0xb0, 0xd5, 0x8f, 0xb1, 0xd1, 0x03, 0xb2, 0x59, 0x8c, 0x0e, 0xc7, 0x69, 0xd6, 0x1e,
	0xa7, 0xe2, 0xfd, 0xad, 0x14, 0xcb, 0x88, 0xf3, 0xb1, 0x3c, 0x8b, 0x0f, 0x2a, 0x4e, 0x66, 0xa2,
	0x1c, 0x2d, 0xd3, 0xc7, 0xa2, 0x38, 0x74, 0x4a, 0xb4, 0x9d, 0x12, 0x5f, 0x9d, 0x12, 0x1f, 0xbd,
	0xca, 0xda, 0x5e, 0x65, 0x9f, 0xbd, 0xca, 0x56, 0xe7, 0xb1, 0xc9, 0xed, 0x77, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xa0, 0xb6, 0x38, 0xc4, 0x58, 0x01, 0x00, 0x00,
}

func (m *ValueState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValueState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValueState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintState(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.ObjectMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintState(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintState(dAtA []byte, offset int, v uint64) int {
	offset -= sovState(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ValueState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ObjectMeta.Size()
	n += 1 + l + sovState(uint64(l))
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	return n
}

func sovState(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozState(x uint64) (n int) {
	return sovState(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ValueState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValueState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValueState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObjectMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = append(m.Value[:0], dAtA[iNdEx:postIndex]...)
			if m.Value == nil {
				m.Value = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipState(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowState
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthState
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupState
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthState
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthState        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowState          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupState = fmt.Errorf("proto: unexpected end of group")
)
