// Code generated by atomix-go-framework. DO NOT EDIT.
package set

import (
	"context"
	primitiveapi "github.com/atomix/atomix-api/go/atomix/primitive"
	set "github.com/atomix/atomix-api/go/atomix/primitive/set"
	"github.com/atomix/atomix-go-framework/pkg/atomix/errors"
	"github.com/atomix/atomix-go-framework/pkg/atomix/logging"
	"github.com/atomix/atomix-go-framework/pkg/atomix/storage/protocol/gossip"
	"github.com/atomix/atomix-go-framework/pkg/atomix/time"
	"google.golang.org/grpc"
)

// RegisterServer registers the primitive on the given node
func RegisterServer(node *gossip.Node) {
	node.RegisterServer(func(server *grpc.Server, manager *gossip.Manager) {
		set.RegisterSetServiceServer(server, newServer(manager))
	})
}

func newServer(manager *gossip.Manager) set.SetServiceServer {
	return &Server{
		manager: manager,
		log:     logging.GetLogger("atomix", "protocol", "gossip", "set"),
	}
}

type Server struct {
	manager *gossip.Manager
	log     logging.Logger
}

func (s *Server) addRequestHeaders(service Service, headers *primitiveapi.RequestHeaders) {
	var timestamp time.Timestamp
	if headers.Timestamp != nil {
		timestamp = service.Protocol().Clock().Update(time.NewTimestamp(*headers.Timestamp))
	} else {
		timestamp = service.Protocol().Clock().Increment()
	}
	timestampProto := service.Protocol().Clock().Scheme().Codec().EncodeTimestamp(timestamp)
	headers.Timestamp = &timestampProto
}

func (s *Server) addResponseHeaders(service Service, headers *primitiveapi.ResponseHeaders) {
	var timestamp time.Timestamp
	if headers.Timestamp != nil {
		timestamp = service.Protocol().Clock().Update(time.NewTimestamp(*headers.Timestamp))
	} else {
		timestamp = service.Protocol().Clock().Increment()
	}
	timestampProto := service.Protocol().Clock().Scheme().Codec().EncodeTimestamp(timestamp)
	headers.Timestamp = &timestampProto
}

func (s *Server) Size(ctx context.Context, request *set.SizeRequest) (*set.SizeResponse, error) {
	s.log.Debugf("Received SizeRequest %+v", request)
	partition, err := s.manager.PartitionFrom(ctx)
	if err != nil {
		s.log.Errorf("Request SizeRequest %+v failed: %v", request, err)
		return nil, err
	}

	serviceID := gossip.ServiceId{
		Type:    gossip.ServiceType(request.Headers.PrimitiveID.Type),
		Cluster: request.Headers.ClusterKey,
		Name:    request.Headers.PrimitiveID.Name,
	}

	service, err := partition.GetService(ctx, serviceID, request.Headers.Timestamp)
	if err != nil {
		s.log.Errorf("Request SizeRequest %+v failed: %v", request, err)
		return nil, errors.Proto(err)
	}

	s.addRequestHeaders(service.(Service), &request.Headers)
	response, err := service.(Service).Size(ctx, request)
	if err != nil {
		s.log.Errorf("Request SizeRequest %+v failed: %v", request, err)
		return nil, errors.Proto(err)
	}
	s.addResponseHeaders(service.(Service), &response.Headers)
	s.log.Debugf("Sending SizeResponse %+v", response)
	return response, nil
}

func (s *Server) Contains(ctx context.Context, request *set.ContainsRequest) (*set.ContainsResponse, error) {
	s.log.Debugf("Received ContainsRequest %+v", request)
	partition, err := s.manager.PartitionFrom(ctx)
	if err != nil {
		s.log.Errorf("Request ContainsRequest %+v failed: %v", request, err)
		return nil, err
	}

	serviceID := gossip.ServiceId{
		Type:    gossip.ServiceType(request.Headers.PrimitiveID.Type),
		Cluster: request.Headers.ClusterKey,
		Name:    request.Headers.PrimitiveID.Name,
	}

	service, err := partition.GetService(ctx, serviceID, request.Headers.Timestamp)
	if err != nil {
		s.log.Errorf("Request ContainsRequest %+v failed: %v", request, err)
		return nil, errors.Proto(err)
	}

	s.addRequestHeaders(service.(Service), &request.Headers)
	response, err := service.(Service).Contains(ctx, request)
	if err != nil {
		s.log.Errorf("Request ContainsRequest %+v failed: %v", request, err)
		return nil, errors.Proto(err)
	}
	s.addResponseHeaders(service.(Service), &response.Headers)
	s.log.Debugf("Sending ContainsResponse %+v", response)
	return response, nil
}

func (s *Server) Add(ctx context.Context, request *set.AddRequest) (*set.AddResponse, error) {
	s.log.Debugf("Received AddRequest %+v", request)
	partition, err := s.manager.PartitionFrom(ctx)
	if err != nil {
		s.log.Errorf("Request AddRequest %+v failed: %v", request, err)
		return nil, err
	}

	serviceID := gossip.ServiceId{
		Type:    gossip.ServiceType(request.Headers.PrimitiveID.Type),
		Cluster: request.Headers.ClusterKey,
		Name:    request.Headers.PrimitiveID.Name,
	}

	service, err := partition.GetService(ctx, serviceID, request.Headers.Timestamp)
	if err != nil {
		s.log.Errorf("Request AddRequest %+v failed: %v", request, err)
		return nil, errors.Proto(err)
	}

	s.addRequestHeaders(service.(Service), &request.Headers)
	response, err := service.(Service).Add(ctx, request)
	if err != nil {
		s.log.Errorf("Request AddRequest %+v failed: %v", request, err)
		return nil, errors.Proto(err)
	}
	s.addResponseHeaders(service.(Service), &response.Headers)
	s.log.Debugf("Sending AddResponse %+v", response)
	return response, nil
}

func (s *Server) Remove(ctx context.Context, request *set.RemoveRequest) (*set.RemoveResponse, error) {
	s.log.Debugf("Received RemoveRequest %+v", request)
	partition, err := s.manager.PartitionFrom(ctx)
	if err != nil {
		s.log.Errorf("Request RemoveRequest %+v failed: %v", request, err)
		return nil, err
	}

	serviceID := gossip.ServiceId{
		Type:    gossip.ServiceType(request.Headers.PrimitiveID.Type),
		Cluster: request.Headers.ClusterKey,
		Name:    request.Headers.PrimitiveID.Name,
	}

	service, err := partition.GetService(ctx, serviceID, request.Headers.Timestamp)
	if err != nil {
		s.log.Errorf("Request RemoveRequest %+v failed: %v", request, err)
		return nil, errors.Proto(err)
	}

	s.addRequestHeaders(service.(Service), &request.Headers)
	response, err := service.(Service).Remove(ctx, request)
	if err != nil {
		s.log.Errorf("Request RemoveRequest %+v failed: %v", request, err)
		return nil, errors.Proto(err)
	}
	s.addResponseHeaders(service.(Service), &response.Headers)
	s.log.Debugf("Sending RemoveResponse %+v", response)
	return response, nil
}

func (s *Server) Clear(ctx context.Context, request *set.ClearRequest) (*set.ClearResponse, error) {
	s.log.Debugf("Received ClearRequest %+v", request)
	partition, err := s.manager.PartitionFrom(ctx)
	if err != nil {
		s.log.Errorf("Request ClearRequest %+v failed: %v", request, err)
		return nil, err
	}

	serviceID := gossip.ServiceId{
		Type:    gossip.ServiceType(request.Headers.PrimitiveID.Type),
		Cluster: request.Headers.ClusterKey,
		Name:    request.Headers.PrimitiveID.Name,
	}

	service, err := partition.GetService(ctx, serviceID, request.Headers.Timestamp)
	if err != nil {
		s.log.Errorf("Request ClearRequest %+v failed: %v", request, err)
		return nil, errors.Proto(err)
	}

	s.addRequestHeaders(service.(Service), &request.Headers)
	response, err := service.(Service).Clear(ctx, request)
	if err != nil {
		s.log.Errorf("Request ClearRequest %+v failed: %v", request, err)
		return nil, errors.Proto(err)
	}
	s.addResponseHeaders(service.(Service), &response.Headers)
	s.log.Debugf("Sending ClearResponse %+v", response)
	return response, nil
}

func (s *Server) Events(request *set.EventsRequest, srv set.SetService_EventsServer) error {
	s.log.Debugf("Received EventsRequest %+v", request)
	partition, err := s.manager.PartitionFrom(srv.Context())
	if err != nil {
		s.log.Errorf("Request EventsRequest %+v failed: %v", request, err)
		return errors.Proto(err)
	}

	serviceID := gossip.ServiceId{
		Type:    gossip.ServiceType(request.Headers.PrimitiveID.Type),
		Cluster: request.Headers.ClusterKey,
		Name:    request.Headers.PrimitiveID.Name,
	}

	service, err := partition.GetService(srv.Context(), serviceID, request.Headers.Timestamp)
	if err != nil {
		s.log.Errorf("Request EventsRequest %+v failed: %v", request, err)
		return err
	}

	s.addRequestHeaders(service.(Service), &request.Headers)

	responseCh := make(chan set.EventsResponse)
	errCh := make(chan error)
	go func() {
		err := service.(Service).Events(srv.Context(), request, responseCh)
		if err != nil {
			errCh <- err
		}
		close(errCh)
	}()

	for {
		select {
		case response, ok := <-responseCh:
			if ok {
				s.addResponseHeaders(service.(Service), &response.Headers)
				s.log.Debugf("Sending EventsResponse %v", response)
				err = srv.Send(&response)
				if err != nil {
					s.log.Errorf("Request EventsRequest %+v failed: %v", request, err)
					return errors.Proto(err)
				}
			} else {
				s.log.Debugf("Finished EventsRequest %+v", request)
				return nil
			}
		case <-srv.Context().Done():
			s.log.Debugf("Finished EventsRequest %+v", request)
			return nil
		}
	}
}

func (s *Server) Elements(request *set.ElementsRequest, srv set.SetService_ElementsServer) error {
	s.log.Debugf("Received ElementsRequest %+v", request)
	partition, err := s.manager.PartitionFrom(srv.Context())
	if err != nil {
		s.log.Errorf("Request ElementsRequest %+v failed: %v", request, err)
		return errors.Proto(err)
	}

	serviceID := gossip.ServiceId{
		Type:    gossip.ServiceType(request.Headers.PrimitiveID.Type),
		Cluster: request.Headers.ClusterKey,
		Name:    request.Headers.PrimitiveID.Name,
	}

	service, err := partition.GetService(srv.Context(), serviceID, request.Headers.Timestamp)
	if err != nil {
		s.log.Errorf("Request ElementsRequest %+v failed: %v", request, err)
		return err
	}

	s.addRequestHeaders(service.(Service), &request.Headers)

	responseCh := make(chan set.ElementsResponse)
	errCh := make(chan error)
	go func() {
		err := service.(Service).Elements(srv.Context(), request, responseCh)
		if err != nil {
			errCh <- err
		}
		close(errCh)
	}()

	for {
		select {
		case response, ok := <-responseCh:
			if ok {
				s.addResponseHeaders(service.(Service), &response.Headers)
				s.log.Debugf("Sending ElementsResponse %v", response)
				err = srv.Send(&response)
				if err != nil {
					s.log.Errorf("Request ElementsRequest %+v failed: %v", request, err)
					return errors.Proto(err)
				}
			} else {
				s.log.Debugf("Finished ElementsRequest %+v", request)
				return nil
			}
		case <-srv.Context().Done():
			s.log.Debugf("Finished ElementsRequest %+v", request)
			return nil
		}
	}
}
